name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  XCODE_VERSION: ^26.0

jobs:
  test:
    name: Run tests
    runs-on: macos-15

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.swiftpm
          key: ${{ runner.os }}-packages-${{ hashFiles('Package.resolved') }}
          restore-keys: ${{ runner.os }}-packages-
      - name: Lint
        run: swift package plugin --allow-writing-to-package-directory swiftlint --strict Sources/ Tests/
      - name: Run tests
        run: swift test
